### ISSUE TITLE
build failure: conflicting types for EvmuTimestamp

### ISSUE THREAD

**Issue by buhman** [gyrovorbis/libevmu#14]
It appears this is a regression introduced by https://github.com/gyrovorbis/libevmu/commit/0700e052867192ed1d8cd9af310a1249ee16d815
```
In file included from /home/bilbo/libevmu/lib/source/fs/evmu_file_manager.c:4:
/home/bilbo/libevmu/lib/api/evmu/fs/evmu_vmi.h:82:3: error: conflicting types for ‘EvmuTimestamp’; have ‘struct EvmuVmiTimestamp’
   82 | } EvmuTimestamp;
      |   ^~~~~~~~~~~~~
In file included from /home/bilbo/libevmu/lib/api/evmu/fs/evmu_fat.h:30,
                 from /home/bilbo/libevmu/lib/api/evmu/fs/evmu_file_manager.h:15,
                 from /home/bilbo/libevmu/lib/source/fs/evmu_file_manager.c:1:
/home/bilbo/libevmu/lib/api/evmu/fs/evmu_fs_utils.h:63:3: note: previous declaration of ‘EvmuTimestamp’ with type ‘EvmuTimestamp’
   63 | } EvmuTimestamp;
      |   ^~~~~~~~~~~~~
[ 82%] Building C object lib/CMakeFiles/libLibElysianVMU.dir/source/fs/evmu_nexus.c.o
/home/bilbo/libevmu/lib/api/evmu/fs/evmu_vmi.h:101:5: error: unknown type name ‘EvmuVmiTimestamp’; did you mean ‘EvmuTimestamp’?
  101 |     EvmuVmiTimestamp    creationTimestamp;                            //!< File creation date
      |     ^~~~~~~~~~~~~~~~
      |     EvmuTimestamp
In file included from /home/bilbo/libevmu/lib/lib/libgimbal/lib/api/gimbal/core/../algorithms/../core/../preprocessor/gimbal_macro_utils.h:12,
                 from /home/bilbo/libevmu/lib/lib/libgimbal/lib/api/gimbal/core/../algorithms/../core/gimbal_decls.h:13,
                 from /home/bilbo/libevmu/lib/lib/libgimbal/lib/api/gimbal/core/../algorithms/gimbal_numeric.h:12,
                 from /home/bilbo/libevmu/lib/lib/libgimbal/lib/api/gimbal/core/gimbal_ctx.h:10,
                 from /home/bilbo/libevmu/lib/api/evmu/fs/../hw/../types/../evmu_api.h:14,
                 from /home/bilbo/libevmu/lib/api/evmu/fs/../hw/../types/evmu_typedefs.h:11,
                 from /home/bilbo/libevmu/lib/api/evmu/fs/../hw/../types/evmu_ibehavior.h:13,
                 from /home/bilbo/libevmu/lib/api/evmu/fs/../hw/../types/evmu_peripheral.h:15,
                 from /home/bilbo/libevmu/lib/api/evmu/fs/../hw/evmu_flash.h:32,
                 from /home/bilbo/libevmu/lib/api/evmu/fs/evmu_fat.h:29:
/home/bilbo/libevmu/lib/lib/libgimbal/lib/api/gimbal/core/../algorithms/../core/../preprocessor/gimbal_compiler.h:397:45: error: static assertion failed: "sizeof(EvmuVmi) == EVMU_VMI_FILE_SIZE"
  397 | #   define GBL_STATIC_ASSERT(cond)          _Static_assert(cond, #cond);
      |                                             ^~~~~~~~~~~~~~
/home/bilbo/libevmu/lib/api/evmu/fs/evmu_vmi.h:111:1: note: in expansion of macro ‘GBL_STATIC_ASSERT’
  111 | GBL_STATIC_ASSERT(sizeof(EvmuVmi) == EVMU_VMI_FILE_SIZE)
      | ^~~~~~~~~~~~~~~~~
/home/bilbo/libevmu/lib/source/fs/evmu_fat.c: In function ‘EvmuFat_blockLink’:
/home/bilbo/libevmu/lib/source/fs/evmu_fat.c:362:34: warning: initialization discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  362 |     EvmuBlock*      pFatTable  = EvmuFat_blockData(pSelf, tableBlock);
      |                                  ^~~~~~~~~~~~~~~~~
/home/bilbo/libevmu/lib/source/fs/evmu_fat.c: In function ‘EvmuFat_dirEntry’:
/home/bilbo/libevmu/lib/source/fs/evmu_fat.c:438:38: warning: initialization discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  438 |     EvmuDirEntry*         pEntry   = EvmuFat_blockData(pSelf, dirBlock);
      |                                      ^~~~~~~~~~~~~~~~~
At top level:
cc1: note: unrecognized command-line option ‘-Wno-deprecated-volatile’ may have been intended to silence earlier diagnostics
[ 83%] Building C object lib/CMakeFiles/libLibElysianVMU.dir/source/fs/evmu_vms.c.o
[ 84%] Building C object lib/CMakeFiles/libLibElysianVMU.dir/source/hw/evmu_gamepad.c.o
[ 84%] Building C object lib/CMakeFiles/libLibElysianVMU.dir/source/hw/evmu_isa.c.o
In file included from /home/bilbo/libevmu/lib/source/fs/evmu_vmi.c:1:
/home/bilbo/libevmu/lib/api/evmu/fs/evmu_vmi.h:82:3: error: conflicting types for ‘EvmuTimestamp’; have ‘struct EvmuVmiTimestamp’
   82 | } EvmuTimestamp;
      |   ^~~~~~~~~~~~~
In file included from /home/bilbo/libevmu/lib/api/evmu/fs/evmu_fat.h:30,
                 from /home/bilbo/libevmu/lib/api/evmu/fs/evmu_vmi.h:39:
/home/bilbo/libevmu/lib/api/evmu/fs/evmu_fs_utils.h:63:3: note: previous declaration of ‘EvmuTimestamp’ with type ‘EvmuTimestamp’
   63 | } EvmuTimestamp;
      |   ^~~~~~~~~~~~~
/home/bilbo/libevmu/lib/api/evmu/fs/evmu_vmi.h:101:5: error: unknown type name ‘EvmuVmiTimestamp’; did you mean ‘EvmuTimestamp’?
  101 |     EvmuVmiTimestamp    creationTimestamp;                            //!< File creation date
      |     ^~~~~~~~~~~~~~~~
      |     EvmuTimestamp
In file included from /home/bilbo/libevmu/lib/lib/libgimbal/lib/api/gimbal/core/../algorithms/../core/../preprocessor/gimbal_macro_utils.h:12,
                 from /home/bilbo/libevmu/lib/lib/libgimbal/lib/api/gimbal/core/../algorithms/../core/gimbal_decls.h:13,
                 from /home/bilbo/libevmu/lib/lib/libgimbal/lib/api/gimbal/core/../algorithms/gimbal_numeric.h:12,
                 from /home/bilbo/libevmu/lib/lib/libgimbal/lib/api/gimbal/core/gimbal_ctx.h:10,
                 from /home/bilbo/libevmu/lib/api/evmu/fs/../hw/../types/../evmu_api.h:14,
                 from /home/bilbo/libevmu/lib/api/evmu/fs/../hw/../types/evmu_typedefs.h:11,
                 from /home/bilbo/libevmu/lib/api/evmu/fs/../hw/../types/evmu_ibehavior.h:13,
                 from /home/bilbo/libevmu/lib/api/evmu/fs/../hw/../types/evmu_peripheral.h:15,
                 from /home/bilbo/libevmu/lib/api/evmu/fs/../hw/evmu_flash.h:32,
                 from /home/bilbo/libevmu/lib/api/evmu/fs/evmu_fat.h:29:
/home/bilbo/libevmu/lib/lib/libgimbal/lib/api/gimbal/core/../algorithms/../core/../preprocessor/gimbal_compiler.h:397:45: error: static assertion failed: "sizeof(EvmuVmi) == EVMU_VMI_FILE_SIZE"
  397 | #   define GBL_STATIC_ASSERT(cond)          _Static_assert(cond, #cond);
      |                                             ^~~~~~~~~~~~~~
/home/bilbo/libevmu/lib/api/evmu/fs/evmu_vmi.h:111:1: note: in expansion of macro ‘GBL_STATIC_ASSERT’
  111 | GBL_STATIC_ASSERT(sizeof(EvmuVmi) == EVMU_VMI_FILE_SIZE)
      | ^~~~~~~~~~~~~~~~~
/home/bilbo/libevmu/lib/source/fs/evmu_vmi.c: In function ‘EvmuVmi_creation’:
/home/bilbo/libevmu/lib/source/fs/evmu_vmi.c:31:12: error: implicit declaration of function ‘EvmuVmiTimestamp_dateTime’; did you mean ‘EvmuTimestamp_dateTime’? [-Wimplicit-function-declaration]
   31 |     return EvmuVmiTimestamp_dateTime(&pSelf->creationTimestamp, pDateTime);
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~
      |            EvmuTimestamp_dateTime
/home/bilbo/libevmu/lib/source/fs/evmu_vmi.c:31:12: error: returning ‘int’ from a function with return type ‘GblDateTime *’ {aka ‘struct GblDateTime *’} makes pointer from integer without a cast [-Wint-conversion]
   31 |     return EvmuVmiTimestamp_dateTime(&pSelf->creationTimestamp, pDateTime);
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/bilbo/libevmu/lib/source/fs/evmu_vmi.c: In function ‘EvmuVmi_setCreation’:
/home/bilbo/libevmu/lib/source/fs/evmu_vmi.c:68:5: error: implicit declaration of function ‘EvmuVmiTimestamp_setDateTime’; did you mean ‘EvmuTimestamp_setDateTime’? [-Wimplicit-function-declaration]
   68 |     EvmuVmiTimestamp_setDateTime(&pSelf->creationTimestamp, pDateTime);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     EvmuTimestamp_setDateTime
/home/bilbo/libevmu/lib/source/fs/evmu_vmi.c: At top level:
/home/bilbo/libevmu/lib/source/fs/evmu_vmi.c:117:47: error: unknown type name ‘EvmuVmiTimestamp’; did you mean ‘EvmuTimestamp’?
  117 | EVMU_EXPORT void EvmuVmiTimestamp_setDateTime(EvmuVmiTimestamp* pSelf, const GblDateTime* pDateTime) {
      |                                               ^~~~~~~~~~~~~~~~
      |                                               EvmuTimestamp
/home/bilbo/libevmu/lib/source/fs/evmu_vmi.c:127:58: error: unknown type name ‘EvmuVmiTimestamp’; did you mean ‘EvmuTimestamp’?
  127 | EVMU_EXPORT GblDateTime* EvmuVmiTimestamp_dateTime(const EvmuVmiTimestamp* pSelf, GblDateTime* pDateTime) {
      |                                                          ^~~~~~~~~~~~~~~~
      |                                                          EvmuTimestamp
/home/bilbo/libevmu/lib/source/fs/evmu_vmi.c:127:26: error: conflicting types for ‘EvmuVmiTimestamp_dateTime’; have ‘GblDateTime *(const int *, GblDateTime *)’ {aka ‘struct GblDateTime *(const int *, struct GblDateTime *)’}
  127 | EVMU_EXPORT GblDateTime* EvmuVmiTimestamp_dateTime(const EvmuVmiTimestamp* pSelf, GblDateTime* pDateTime) {
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/bilbo/libevmu/lib/source/fs/evmu_vmi.c:31:12: note: previous implicit declaration of ‘EvmuVmiTimestamp_dateTime’ with type ‘int()’
   31 |     return EvmuVmiTimestamp_dateTime(&pSelf->creationTimestamp, pDateTime);
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/bilbo/libevmu/lib/source/fs/evmu_vmi.c: In function ‘EvmuVmiTimestamp_dateTime’:
/home/bilbo/libevmu/lib/source/fs/evmu_vmi.c:128:37: error: request for member ‘year’ in something not a structure or union
  128 |     pDateTime->date.year     = pSelf->year;
      |                                     ^~
/home/bilbo/libevmu/lib/source/fs/evmu_vmi.c:129:37: error: request for member ‘month’ in something not a structure or union
  129 |     pDateTime->date.month    = pSelf->month;
      |                                     ^~
/home/bilbo/libevmu/lib/source/fs/evmu_vmi.c:130:37: error: request for member ‘day’ in something not a structure or union
  130 |     pDateTime->date.day      = pSelf->day;
      |                                     ^~
/home/bilbo/libevmu/lib/source/fs/evmu_vmi.c:131:37: error: request for member ‘hour’ in something not a structure or union
  131 |     pDateTime->time.hours    = pSelf->hour;
      |                                     ^~
/home/bilbo/libevmu/lib/source/fs/evmu_vmi.c:132:37: error: request for member ‘minute’ in something not a structure or union
  132 |     pDateTime->time.minutes  = pSelf->minute;
      |                                     ^~
/home/bilbo/libevmu/lib/source/fs/evmu_vmi.c:133:37: error: request for member ‘second’ in something not a structure or union
  133 |     pDateTime->time.seconds  = pSelf->second;
      |                                     ^~
/home/bilbo/libevmu/lib/source/fs/evmu_file_manager.c: In function ‘EvmuFileManager_read’:
/home/bilbo/libevmu/lib/source/fs/evmu_file_manager.c:151:26: warning: dereferencing ‘void *’ pointer
  151 |             memcpy(&pData[bytesRead], data, byteCount);
      |                          ^
/home/bilbo/libevmu/lib/source/fs/evmu_file_manager.c: In function ‘EvmuFileManager_defrag’:
/home/bilbo/libevmu/lib/source/fs/evmu_file_manager.c:336:47: error: passing argument 2 of ‘EvmuFileManager_alloc’ from incompatible pointer type [-Wincompatible-pointer-types]
  336 |                                               &fileProperties,
      |                                               ^~~~~~~~~~~~~~~
      |                                               |
      |                                               VMUFlashNewFileProperties *
/home/bilbo/libevmu/lib/api/evmu/fs/evmu_file_manager.h:121:68: note: expected ‘EvmuNewFileInfo *’ {aka ‘struct EvmuNewFileInfo *’} but argument is of type ‘VMUFlashNewFileProperties *’
  121 |                                                   EvmuNewFileInfo* pInfo,
      |                                                   ~~~~~~~~~~~~~~~~~^~~~~
At top level:
cc1: note: unrecognized command-line option ‘-Wno-deprecated-volatile’ may have been intended to silence earlier diagnostics
[ 85%] Building C object lib/CMakeFiles/libLibElysianVMU.dir/source/hw/evmu_pic.c.o
make[2]: *** [lib/CMakeFiles/libLibElysianVMU.dir/build.make:219: lib/CMakeFiles/libLibElysianVMU.dir/source/fs/evmu_vmi.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/bilbo/libevmu/lib/source/fs/evmu_file_manager.c: In function ‘EvmuFileManager_write’:
/home/bilbo/libevmu/lib/source/fs/evmu_file_manager.c:626:51: warning: dereferencing ‘void *’ pointer
  626 |                                           &pBuffer[bytesWritten],
      |                                                   ^
/home/bilbo/libevmu/lib/lib/libgimbal/lib/api/gimbal/core/gimbal_ctx.h:523:58: note: in definition of macro ‘GBL_CTX_CALL_N’
  523 |         GBL_MAYBE_UNUSED const GBL_RESULT localResult = (funcCall);             \
      |                                                          ^~~~~~~~
/home/bilbo/libevmu/lib/lib/libgimbal/lib/api/gimbal/core/../algorithms/../core/../preprocessor/gimbal_macro_composition.h:25:41: note: in expansion of macro ‘GBL_CTX_CALL_2’
   25 | #define GBL_CAT(A, B)                   A##B
      |                                         ^
/home/bilbo/libevmu/lib/source/fs/evmu_file_manager.c:624:9: note: in expansion of macro ‘GBL_CTX_CALL’
  624 |         GBL_CTX_CALL(EvmuFlash_writeBytes(pFlash,
      |         ^~~~~~~~~~~~
At top level:
cc1: note: unrecognized command-line option ‘-Wno-deprecated-volatile’ may have been intended to silence earlier diagnostics
make[2]: *** [lib/CMakeFiles/libLibElysianVMU.dir/build.make:205: lib/CMakeFiles/libLibElysianVMU.dir/source/fs/evmu_file_manager.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:218: lib/CMakeFiles/libLibElysianVMU.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

**Comment by gyrovorbis** [comment]
Thank you! On it!

**Comment by andressbarajas** [comment]
Fixed by commit: ec9cbccf6fa77f11a656d0048b349dae1d152521
